# Generated by Django 3.2.9 on 2021-12-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sid', models.CharField(max_length=26)),
                ('user_id', models.TextField()),
                ('Class', models.CharField(max_length=25)),
                ('Dormitory', models.CharField(choices=[('Menengai', 'Menengai'), ('Satima', 'Satima'), ('Batian', 'Batian'), ('Lenana', 'Lenana')], default='doms', max_length=25)),
            ],
        ),
    ]
